// Generated by Wrangler on Sun Jun 16 2024 05:32:21 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	DOCKERHUB_ACCESS_DOMAIN: "dhcr.example-access.com";
	K8S_ACCESS_DOMAIN: "k8s.example-access.com";
	QUAY_ACCESS_DOMAIN: "quay.example-access.com";
	GCR_ACCESS_DOMAIN: "gcr.example-access.com";
	GHCR_ACCESS_DOMAIN: "ghcr.example-access.com";
	ELASTIC_ACCESS_DOMAIN: "elastic.example-access.com";
	CRUNCHYDATA_ACCESS_DOMAIN: "crunchydata.example-access.com";
	NVCR_ACCESS_DOMAIN: "nvcr.example-access.com";
	LSCR_ACCESS_DOMAIN: "lscr.example-access.com";
	MCR_ACCESS_DOMAIN: "mcr.example-access.com";
}
